{% set version = "4.3.0" %}

package:
  name: netcdf-cxx4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-cxx4/archive/v{{ version }}.tar.gz
  sha256: 25da1c97d7a01bc4cee34121c32909872edd38404589c0427fefa1301743f18f

build:
  number: 10
  skip: True  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libnetcdf
    - hdf5
  run:
    - libnetcdf
    - hdf5

test:
  commands:
    #- ncxx4-config --all  # FIXME: no ncxx4-config for cmake yet.
    - test -f ${PREFIX}/lib/libnetcdf-cxx4.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf_c++4.a  # [not win]

about:
  home: https://github.com/Unidata/netcdf-cxx4
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  license_file: COPYRIGHT
  summary: Unidata NetCDF C++ Library

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
