{% set version = "4.3.0" %}

package:
  name: netcdf-cxx4
  version: {{ version }}

source:
  fn: netcdf-cxx4-{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-cxx4/archive/v{{ version }}.tar.gz
  sha256: 25da1c97d7a01bc4cee34121c32909872edd38404589c0427fefa1301743f18f
  patches:
    - ncxx4-config.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - toolchain
    - libnetcdf 4.4*
  run:
    - libnetcdf 4.4*

test:
  commands:
    - ncxx4-config --all

about:
  home: https://github.com/Unidata/netcdf-cxx4
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: Unidata NetCDF C++ Library

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
