travis:
  secure:
    BINSTAR_TOKEN: f2KKRWodXAn8se33uu72wsJEq4d60cJAN491a0a5+iktPVmvxOD4aYtdBReD/QzRBWxwlw7MJU47Jug/CL/sKJ1OuMWL15eGUlU3RWPd+mCMUeWSDiF6B226a7CnejYKSyu85MBW2kV8RtiVmIZXOEXZ5MPi0cuCRxohbya+3Elz15Hl2tOdHkTFGYrycM6qqDpDLScZSoKP5B4o2I/pNZPORebNWG6SBPsLUMWUpccPb4cKdPWm4dvb5fuo7ia72R5dyUmQeXDH9+9dNpYaM3jHm2lk5Rav8urT+NVvCX4R4K8/Z0snHXcRgU3MNq1oJUIm0Rygk+rYpNZlhRmUWcwPHUR7G4QKEg8zRrKCc0osyug2KvhIAMGGx9aTxdICp+fY8eCakNPrHxlr+OHi8Fulv5RWWVY4aO1fiGdeaUWJeGICbm77SI5dBVNoYcKSyHKZ3KucoM+cDnXiJCRE3kFaBBiWWjmLUXsScc4y3a6xqAmZEf8ryw5g8mh+B4JjU7hGes36Cj6dL9l283V0s0rHU9jMvuUrvLb3Xo3ZmSC8uIX4tlYUreR7Lxj/tZbRYxJl15aT7URzB777K+QEiaT5uHCG5f0dv4aWPP7ZqN/6CnOo4WmJ19ppQtCUhTuJuz+R2qimMwCYzaIsYTDUpY41TDv/boHZx7fY6pyO3pI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
